apiVersion: v1
kind: Service
metadata:
  name: publicreverseproxy
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app: reverseproxy
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP